In [1]:
from PIL import Image
import os
import numpy as np
import pandas as pd

In [3]:
img = np.array(Image.open('Image/m_3009743_sw_14_060_20201018.tif'))
img.shape

C:\Users\18382\anaconda3\lib\site-packages\PIL\Image.py:2896: DecompressionBombWarning: Image size (133302400 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(

(12320, 10820, 4)

In [4]:
def find_area(img, x, y, d=1):
    return img[max(0, x-d):x+d+1, max(0, y-d):y+d+1].astype(int)

In [5]:
x = pd.DataFrame({'x':np.random.choice(img.shape[0], 500)})
y = pd.DataFrame({'y':np.random.choice(img.shape[1], 500)})

# cross join
df = x.assign(foo = 1).merge(y.assign(foo = 1), on = 'foo').drop(columns = ['foo'])

In [7]:
df[['r', 'g', 'b', 'l']] = pd.DataFrame(df.apply(
    lambda x:img[int(x['x']), int(x['y'])].astype(int), axis = 1).tolist())

df[['r_avg', 'g_avg', 'b_avg', 'l_avg']] = pd.DataFrame(
    df.apply(lambda x:np.average(find_area(img, int(x['x']), int(x['y']), 2), axis = (0,1)), axis = 1).tolist())

df[['r_std', 'g_std', 'b_std', 'l_std']] = pd.DataFrame(
    df.apply(lambda x:np.std(find_area(img, int(x['x']), int(x['y']), 2), axis = (0,1)), axis = 1).tolist())

In [8]:
df

,x,y,r,g,b,l,r_avg,g_avg,b_avg,l_avg,r_std,g_std,b_std,l_std
0,1411,10796,93,101,104,61,95.52,103.56,104.92,62.68,5.177799,5.036507,3.676085,5.725172
1,1411,8635,77,83,87,51,68.84,74.36,81.92,44.52,15.719237,14.307704,9.674379,13.106090
2,1411,4257,46,50,67,19,46.32,51.84,67.56,22.52,3.258466,2.508864,2.192350,5.783563
3,1411,3069,69,78,72,137,95.20,97.60,90.84,133.08,19.921847,16.523922,15.650380,12.664659
4,1411,2265,186,187,181,159,177.52,178.48,171.76,160.04,17.353086,17.376122,20.813995,4.449539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249995,378,8476,70,84,75,174,72.08,83.48,76.44,158.48,13.968307,10.617420,7.386907,17.376122
249996,378,3181,112,114,91,155,115.52,115.44,92.12,155.60,4.001200,2.192350,1.840000,1.296148
249997,378,232,59,74,67,165,65.12,79.88,68.60,175.44,5.757222,5.515941,1.854724,5.246561
249998,378,7421,111,115,110,77,103.92,107.12,106.44,69.88,20.163174,18.424592,12.803375,20.000640
249999,378,9071,64,79,68,176,63.60,75.64,68.24,162.72,9.178235,9.727816,3.444184,15.193472